export {entityClassWithDeleteMethodServicesAndUtilitiesFabric} from './entityClassWithDeleteMethodServicesAndUtilitiesFabric';

export {runTestEntityClassWithDeleteMethodServicesAndUtilitiesFabric} from './entityClassWithDeleteMethodServicesAndUtilitiesFabric.runTest';
